services:
  frontend:
    build: frontend

  backend:
    depends_on:
      - database
    build: backend

  database:
    build: database

  proxy:
    depends_on:
      - frontend
      - backend
    build: proxy
    ports:
      - "80:80"
